Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Controllers/ModularWizardJsController.cs
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace Jlw.ModularContent.Areas.ModularContentWizardAdmin.Controllers
{
    public class ModularWizardJsController : Controller
    {
        protected IRazorViewEngine _razorViewEngine;
        public ModularWizardJsController(IRazorViewEngine razorEngine)
        {
            _razorViewEngine = razorEngine;
        }

        [AllowAnonymous]
        [HttpGet("~/" + ModularWizardExtensions.AreaName + "/js/wizardLibScript.js")]
        public virtual IActionResult WizardLibScript()
        {
            // Create ActionContext to use with ViewContext
            var ctx = new ActionContext(HttpContext, ControllerContext.RouteData, ControllerContext.ActionDescriptor);
            // Retrieve View template from assembly
            var view = _razorViewEngine.FindView(ctx, "_ModularWizardLibScript.js", true);
            // If view is not found, return 404
            if (view.View is null)
                return new NotFoundResult();

            // Initialize StringBuilder to process view data
            var sb = new StringBuilder();
            // Initialize StringWriter with StringBuilder
            var writer = new StringWriter(sb);

            // Initialize ViewContext with writer for processing
            var viewContext = new ViewContext(ctx, view.View, ViewData, TempData, writer, new HtmlHelperOptions());
            
            // Render view, and write to sb.
            viewContext.View.RenderAsync(viewContext).Wait();

            // Initialize regular expression
            var regEx = new Regex("<[/]?script[^>]*>", RegexOptions.IgnoreCase);

            // Replace script tags in rendered string and output as javascript file
            return new ContentResult()
            {
                ContentType = "application/javascript",
                Content = regEx.Replace(sb.ToString(), "")
            };
        }
    }
}

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Controllers/WizardAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Jlw.Utilities.Data;
using Microsoft.AspNetCore.Mvc;

namespace Jlw.ModularContent.Areas.ModularContentWizardAdmin.Controllers
{
    public abstract class WizardAdminController : Controller
    {
        protected string _groupFilter = null;
        protected ModularWizardAdminSettings DefaultSettings { get; } = new ModularWizardAdminSettings();
        protected IModularWizardFactoryRepository DataRepository;

        protected WizardAdminController(IModularWizardAdminSettings settings, IModularWizardFactoryRepository repository)
        {
            DataRepository = repository;
            DefaultSettings.IsAdmin = settings.IsAdmin;
            DefaultSettings.CanEdit = settings.CanEdit;
            DefaultSettings.CanDelete = settings.CanDelete;
            DefaultSettings.CanInsert = settings.CanInsert;
            DefaultSettings.UseWysiwyg = settings.UseWysiwyg;
            DefaultSettings.ShowWireFrame = settings.ShowWireFrame;
            DefaultSettings.WireFrameDefault = settings.WireFrameDefault;
            DefaultSettings.TinyMceSettings = settings.TinyMceSettings;
            DefaultSettings.PageTitle = settings.PageTitle;
            DefaultSettings.ExtraCss = settings.ExtraCss;
            DefaultSettings.ExtraScript = settings.ExtraScript;
            DefaultSettings.Area = settings.Area;
            DefaultSettings.ControllerName = settings.ControllerName;
            DefaultSettings.JsRoot = settings.JsRoot;
            DefaultSettings.ToolboxHeight = settings.ToolboxHeight;
            DefaultSettings.HiddenFilterPrefix = settings.HiddenFilterPrefix;
            DefaultSettings.PreviewRecordData = settings.PreviewRecordData;

            DefaultSettings.LanguageList.Clear();
            DefaultSettings.LanguageList.AddRange(settings.LanguageList);

            DefaultSettings.ShowSideNav = settings.ShowSideNav;
            DefaultSettings.SideNavDefault = settings.SideNavDefault;
            DefaultSettings.SideNav.Clear();
            DefaultSettings.SideNav.AddRange(settings.SideNav.Items);
            
            DefaultSettings.AdminUrl = settings.AdminUrl;
            DefaultSettings.ApiOverrideUrl = settings.ApiOverrideUrl;
            DefaultSettings.PreviewUrl = settings.PreviewUrl;
            DefaultSettings.PreviewScreenUrl = settings.PreviewScreenUrl;
            DefaultSettings.ExportUrl = settings.ExportUrl;

        }

        /// <summary>Default route for admin</summary>
        /// <returns>ActionResult.</returns>
        [HttpGet]
        // GET: Default 
        public virtual ActionResult Index()
        {
            return GetViewResult("Index");
        }

        [HttpGet("Preview")]
        public virtual ActionResult Preview()
        {
	        var auth = TestAuthDenial(); // Check to see if user has permissions. (Method returns null if authorized, or an ActionResult if not authorized)
	        if (auth != null) return auth;

	        var settings = new ModularWizardPreviewSettings(DefaultSettings);
            settings.SideNav.Add(new ModularWizardSideNavItem(new ModularWizardContentField(new {Label = "Instructions", FieldType="SCREEN"})));
            return GetViewResult("Preview", settings);
        }

        [HttpGet("Export/{wizardName?}/{screenName?}")]
        public virtual ActionResult Export(string wizardName = null, string screenName = null)
        {
	        var auth = TestAuthDenial(); // Check to see if user has permissions. (Method returns null if authorized, or an ActionResult if not authorized)
	        if (auth != null) return auth;
	        if ((auth = TestAuthDenial(DefaultSettings.CanExport, DefaultSettings)) != null) return auth;

			StringBuilder sb = new StringBuilder();
            IEnumerable<IModularContentField> fieldData;
            if (string.IsNullOrWhiteSpace(screenName))
                fieldData = DataRepository.GetWizardFields(wizardName, _groupFilter);
            else
                fieldData = DataRepository.GetWizardFields(wizardName, screenName, "EN", _groupFilter);

            IEnumerable<IModularContentText> aLangValues = DataRepository.GetLanguageValues(wizardName);
            IEnumerable<IModularContentText> aErrorValues = DataRepository.GetLanguageValues(wizardName + "_Errors");
            List<IModularContentText> aLanguageFields = new List<IModularContentText>();

            foreach (var field in fieldData)
            {
                var langRange = aLangValues?.Where(x => (x.FieldKey.Equals(field.FieldKey) && x.ParentKey.Equals(field.ParentKey)))?.ToArray();

                if (langRange?.Any() ?? false)
                    aLanguageFields.AddRange(langRange);

                langRange = aErrorValues?.Where(x => (x.ParentKey.Equals(field.FieldKey)))?.ToArray();

                if (langRange?.Any() ?? false)
                    aLanguageFields.AddRange(langRange);

                sb.AppendLine($"INSERT INTO [dbo].[LocalizedContentFields] ([GroupKey], [FieldKey], [FieldType], [FieldData], [FieldClass], [ParentKey], [DefaultLabel], [WrapperClass], [WrapperHtmlStart], [WrapperHtmlEnd], [AuditChangeType], [AuditChangeBy], [AuditChangeDate], [Order]) VALUES (" +
                              $"{(field.GroupKey == null ? "null" : $"N'{field.GroupKey.Replace("'", "''")}'")}, " +
                              $"{(field.FieldKey == null ? "null" : $"N'{field.FieldKey.Replace("'", "''")}'")}, " +
                              $"{(field.FieldType == null ? "null" : $"N'{field.FieldType.Replace("'", "''")}'")}, " +
                              $"{(field.FieldData == null ? "null" : $"N'{field.FieldData.Replace("'", "''")}'")}, " +
                              $"{(field.FieldClass == null ? "null" : $"N'{field.FieldClass.Replace("'", "''")}'")}, " +
                              $"{(field.ParentKey == null ? "null" : $"N'{field.ParentKey.Replace("'", "''")}'")}, " +
                              $"{(field.DefaultLabel == null ? "null" : $"N'{field.DefaultLabel.Replace("'", "''")}'")}, " +
                              $"{(field.WrapperClass == null ? "null" : $"N'{field.WrapperClass.Replace("'", "''")}'")}, " +
                              $"{(field.WrapperHtmlStart == null ? "null" : $"N'{field.WrapperHtmlStart.Replace("'", "''")}'")}, " +
                              $"{(field.WrapperHtmlEnd == null ? "null" : $"N'{field.WrapperHtmlStart.Replace("'", "''")}'")}, " +
                              $"{(field.AuditChangeType == null ? "null" : $"N'{field.AuditChangeType.Replace("'", "''")}'")}, " +
                              $"{(field.AuditChangeBy == null ? "null" : $"N'{field.AuditChangeBy.Replace("'", "''")}'")}, " +
                              $"N'{field.AuditChangeDate.ToString("yyyy-MM-dd HH:mm:ss")}', " +
                              $"N'{field.Order}'" +
                              $");");
            }

            foreach (var field in aLanguageFields)
            {
                sb.AppendLine($"INSERT INTO [dbo].[LocalizedContentText] ([GroupKey], [FieldKey], [Language], [Text], [AuditChangeType], [AuditChangeBy], [AuditChangeDate], [ParentKey]) VALUES (" +
                              $"{(field.GroupKey == null ? "null" : $"N'{field.GroupKey.Replace("'", "''")}'")}, " +
                              $"{(field.FieldKey == null ? "null" : $"N'{field.FieldKey.Replace("'", "''")}'")}, " +
                              $"{(field.Language == null ? "null" : $"N'{field.Language.Replace("'", "''")}'")}, " +
                              $"{(field.Text == null ? "null" : $"N'{field.Text.Replace("'", "''")}'")}, " +
                              $"{(field.AuditChangeType == null ? "null" : $"N'{field.AuditChangeType.Replace("'", "''")}'")}, " +
                              $"{(field.AuditChangeBy == null ? "null" : $"N'{field.AuditChangeBy.Replace("'", "''")}'")}, " +
                              $"N'{field.AuditChangeDate.ToString("yyyy-MM-dd HH:mm:ss")}', " +
                              $"{(field.ParentKey == null ? "null" : $"N'{field.ParentKey.Replace("'", "''")}'")}" +
                              $");");
            }
                
            byte[] aBytes = Encoding.ASCII.GetBytes(sb.ToString());
            return new FileContentResult(aBytes, "text/plain")
            {
                FileDownloadName = $"{wizardName}-{DateTime.Now.Ticks}.sql"
            };
        }

        [HttpGet("PreviewScreen/{wizardName?}/{screenName?}")]
        public virtual ActionResult PreviewScreen(string wizardName = null, string screenName = null)
        {
            return GetPreviewScreen(wizardName, screenName, DefaultSettings, new { });
        }

        [NonAction]
        public virtual ActionResult GetPreviewScreen(string wizardName, string screenName, IModularWizardAdminSettings settings, object recordData)
        {
	        var auth = TestAuthDenial(); // Check to see if user has permissions. (Method returns null if authorized, or an ActionResult if not authorized)
	        if (auth != null) return auth;
	        if ((auth = TestAuthDenial(DefaultSettings.CanPreview, DefaultSettings)) != null) return auth;

			var fields = DataRepository?.GetWizardFields(wizardName, _groupFilter);
            var model = new ModularWizardPreviewSettings(settings ?? DefaultSettings, fields, recordData ?? new {})
            {
                ShowWireFrame = DataUtility.ParseBool(Request.Query["wireframe"]),
                ShowSideNav = DataUtility.ParseBool(Request.Query["showNav"]),
                Wizard = wizardName ?? "",
                Screen = screenName ?? ""
            };

            return View(GetViewPath("PreviewScreen"), model);
        }

        /// <summary>Gets the view result.</summary>
        /// <param name="viewName">Name of the view</param>
        /// <param name="settings">Settings to customize the view</param>
        /// <returns>ActionResult.</returns>
        [NonAction]

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Views/WizardAdmin/NotAuthorized.cshtml
<div class="h1 text-danger">Not Authorized</div>
<p class="text-danger">You do not have permission to access this resource.</p>

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Views/WizardAdmin/PreviewScreen.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Jlw.Utilities.Data
@using Microsoft.Extensions.DependencyInjection
@using Jlw.ModularContent
@inject IModularWizardFactoryRepository FactoryRepository
@model ModularWizardPreviewSettings
@{
    ViewData["Title"] = "Preview Screen";
    Layout = "_EmptyLayout";
    string jsRoot = ModularContentExtensions.AreaName;
    string apiUrl = (string.IsNullOrWhiteSpace(Model?.ApiOverrideUrl) ? Url.Action("Index", Model?.ApiControllerName ?? "Api", new { Area = Model?.Area, groupKey = (string)null, fieldKey = (string)null }) + "/" : Model?.ApiOverrideUrl);

    string version = Model?.Version ?? "";

    string wizardName = string.IsNullOrWhiteSpace(Model.Wizard) ? Model?.DefaultWizard ?? "" : Model.Wizard;
    var sideNav = FactoryRepository.GetWizardSideNavData(wizardName, null, Model?.GroupFilter);
    var modelFields = FactoryRepository.GetWizardModelFields(wizardName, Model?.GroupFilter);


}
<h1>Wizard Preview</h1>
<div class="row @(DataUtility.ParseBool(Model?.ShowWireFrame) ? "bootstrap-sketchy" : "")">
    @if (Model?.ShowSideNav ?? false)
    {
        <div class="d-none d-lg-inline-block col-lg-auto border-right">
            <form method="post">
                <input type="hidden" name="st" value="1" />
                <div class="list-group wizard-nav">
                    @foreach (var item in sideNav)
                    {
                        if (!item.IsHidden && !string.IsNullOrWhiteSpace(item.Label))
                        {
                            <button type="button" data-section="@item.Section" data-step="@item.Step" data-screen="@item.Screen" data-wizard="@item.Wizard" class="list-group-item list-group-item-action @item.ClassName"> @Html.Raw(item.Label)</button>
                        }
                    }
                </div>
            </form>
        </div>
    }
    <div class="col-md wizard-form">
        <form method="post">
            <div class="h3 wizard-heading">@(ViewData["Heading"] ?? ViewData["Title"])</div>
            <div class="wizard-body clearfix">

                <div class="spinner-border spinner-border-sm float-start my-1" role="status"></div>
                <div class="p-0">
                    <div class="h5">&nbsp;Please wait, loading...</div>
                    <input type="hidden" name="IsLivePreview" value="1" />
                    <input type="hidden" name="Wizard" value="@(Model?.Wizard ?? "")" />
                    @{
                        foreach (var field in modelFields)
                        {
                            <input type="hidden" name="@field" value="" />
                        }
                    }
                </div>
            </div>
            <div class="wizard-buttons row clearfix">
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <script src="@Url.Action("WizardLibScript", "ModularWizardJs")?_v=@version"></script>
    <link rel="stylesheet" href="@Url.Content($"~/{jsRoot}/css/bootstrap-sketchy.min.css")?_=@version">
    <script src="@Url.Content($"~/{jsRoot}/js/libJlwUtility.min.js")?_=@version"></script>
    <script src="@Url.Content($"~/{jsRoot}//js/bootbox.min.js")?_=@version"></script>
    <script src="@Url.Content($"~/{jsRoot}/font-awesome/js/all.min.js")?_=@version"></script>
    <script src="@Url.Content($"~/{jsRoot}/font-awesome/js/fontawesome.min.js")?_=@version"></script>
    <script>
        (function(t, $, initOptions, undefined) {

            var wiz = window.libJlwWizardBase(t || new window.libJlwUtility() || {}, $, initOptions, undefined);

            t.wizardFields = [
                "IsLivePreview"
            ];
            //t.initializeWizard = initialize;
            t.urlApiRoot = t.urlApiRoot || t.urlRoot + "api/Wizard";
            t.onRenderWizardFormField = t.onRenderWizardFormField || onRenderWizardFormField;

            var fnOldOnRenderWizard = t.onRenderWizard;
            t.onRenderWizard = function(obj, data, parent) {
                if (typeof (fnOldOnRenderWizard) === "function") fnOldOnRenderWizard(obj, data, parent);

                $('input[name=IsLivePreview]').val("1");
            }


            t.navToScreen = fnNavToScreen;
            t.fnOnClickNav = fnOnClickNav;

	        function fnNavToScreen(screenId) { return t.navTo(screenId, "@(Model?.Wizard ?? "")", "", ""); }


            function fnOnClickNav(evt) {
	            var btn = $(evt.delegateTarget);
	            var section = btn.data('section');
	            var step = btn.data('step');
	            var wizard = "@(Model?.Wizard ?? "")";
	            var screen = btn.data('screen');
	            var fn = btn.data('fnclick');
	            if (fn && typeof t[fn] == 'function') {
		            t[fn](evt);
	            }
	            t.navTo(screen, wizard, section, step);
	            return false;
            }


            if (initOptions)
                initialize(initOptions);

            function initialize(opts) {
                currApplicationId = opts["ApplicationId"];
                var data = opts["formData"] || {};
                t.navToScreen(opts['Screen']).done(function () {
                    t.populateFormData(data, $('.wizard-form'));
                });
            }

        })(window.libSampleWizard = window.libSampleWizard || new window.libJlwUtility() || {}, window.jQuery, {
            'urlRoot': '@Html.Raw(Url.Action("Index", "Home"))',
            'urlApiRoot': '@apiUrl',
            //'debugLevel':11,
            'Screen': '@(Model?.Screen ?? "")',
            'wizardParent': '.wizard-form',
            'formData':  { 'IsLivePreview': '1' }
        });
    </script>
}

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Views/WizardAdmin/_AdminCss.cshtml
<style>
    div[data-field-type=textarea]  {
        min-height: 4em;
    }

    .form-hidden span.d-none {
        display: inline-block !important;
        color: #bbb;
    }

    div[data-field-type=input],
    div[data-field-type=select] {
        position: relative;
    }

    div.form-select[size="2"],
    div.form-select[size="3"],
    div.form-select[size="4"],
    div.form-select[size="5"],
    div.form-select[size="6"],
    div.form-select[size="7"],
    div.form-select[size="8"],
    div.form-select[size="9"],
    div.form-select[size="10"]{
	    overflow-y: scroll;
    }

    div.form-select[size="1"] option:nth-child(n+2),
    div.form-select[size="2"] option:nth-child(n+3),
    div.form-select[size="3"] option:nth-child(n+4),
    div.form-select[size="4"] option:nth-child(n+5),
    div.form-select[size="5"] option:nth-child(n+6),
    div.form-select[size="6"] option:nth-child(n+7),
    div.form-select[size="7"] option:nth-child(n+8),
    div.form-select[size="8"] option:nth-child(n+9),
    div.form-select[size="9"] option:nth-child(n+10),
    div.form-select[size="10"] option:nth-child(n+11),
    div[data-field-type=select]:not([multiple]):not([size]) option:nth-child(n+2),
    div.form-select:not([multiple]):not([size]) option:nth-child(n+2) {
        display: none;
    }

    div[data-field-type=input][type=password]::before
    {
        content: '********';
        float: left;
    }

    div[data-field-type=input][type=phone]::before
    {
        content: '(000) 000-0000';
        float: left;
    }

    div[data-field-type=input][type=phone]::after
    {
        content: '\01F4DE';
        float: right;
    }

    div[data-field-type=input][type=url]::after
    {
        content: '\01F310';
        float: right;
    }

    div[data-field-type=input][type=email]::after
    {
        content: '\01F582';
        float: right;
    }

    div[data-field-type=input][type=search]::after
    {
        content: '\01F50D';
        float: right;
    }



    div[data-field-type=input][type=color] {
        padding: 0.25em;
    }
    div[data-field-type=input][type=color]::after
    {
        content: ' ';
        float: left;
        height: 1.4rem;
        width: 100%;
        border: 1px solid #111;
        border-radius: 3px;
        background:blue;
    }


    div[data-field-type=input][type=month]::after
    {
        content: '\01F5D3';
        float: right;
    }

    div[data-field-type=input][type=week]::after
    {
        content: '\01F4C6';
        float: right;
    }

    div[data-field-type=input][type=time]::after 
    {
        content: '\01F553';
        float: right;
    }

    div[data-field-type=input][type=date]::after, 
    div[data-field-type=input][type=datetime-local]::after
    {
        content: '\01F4C5';
        float: right;
    }

    div[data-field-type=input][type=number]::before {
        content: '\01f891';
        position: absolute;
        font-size:medium;
        right: 0.5em;
        bottom: 0.8em;
    }
    div[data-field-type=input][type=number]::after {
        content: '\01f893';
        position: absolute;
        font-size:medium;
        right: 0.5em;
        top: 0.8em;
    }

    /*
    div[data-field-type=input][type=checkbox],
    div[data-field-type=input][type=radio] {
        display: inline-block;
        margin-left: -0.75em;
    }
    */

    div[data-field-type=input][type=range] {
        border: none !important;
        padding: 0;
    }

        div[data-field-type=input][type=range]::before {
            content: ' ';
            position: absolute;
            height: 10px;
            width: 100%;
            border: none;
            margin: 10px 0;
            top: 0;
            border-radius: 5px;
            background: #DEE2E6;
        }
        div[data-field-type=input][type=range]::after {
            content: ' ';
            position: absolute;
            font-size: 20px;
            top: 0;
            height: 0;
            line-height: 20px;
            vertical-align: top;
            display: block;
            border: #0D6EFD solid 8px;
            width: 0;
            border-radius: 10px;
            margin-top: 7px;
	        margin-left: 33%;
        }

    /*
    div[data-field-type=input][type=radio]::before {
        content: '\002b58\000A0';
        font-size:large;
        vertical-align: baseline;
        display: inline-block;
    }

    div[data-field-type=input][type=checkbox]::before {
        content: '\002610\000A0\000A0';
        font-size: large;
        vertical-align: baseline;
        display: inline-block;
    }
    */

    [id^="jlwContainer-"], [id^="jlwElement-"] {
        cursor: pointer;
    }

    div[data-field-type=select] {
	    display: block;
	    width: 100%;
	    font-weight: 400;
	    line-height: 1.5;
	    color: #212529;
	    background-color: #fff;
	    background-clip: padding-box;
	    border: 1px solid #ced4da;
	    -webkit-appearance: none;
	    -moz-appearance: none;
	    appearance: none;
	    border-radius: 0.25rem;
	    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;

	    min-height: calc(1.5em + 0.5rem + 2px);
	    padding: 0.25rem 0.5rem;
	    font-size: .875rem;
	    border-radius: 0.2rem;
    }

</style>

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Views/WizardAdmin/_DataTableLanguageList.cshtml
<div id="jlw-dtlist-localizedcontenttext">
    <div class="row"> 
        <div class="col-sm-12"> 
            <table class="table table-bordered table-sm table-striped table-hover jlw-datatable jlw-datatable-localizedcontenttext"  data-searching='false' data-ordering='false' data-paging="false" data-info="false" width="100%"> 
                <thead> 
                <tr>
                    <th data-data="GroupKey" data-visible="false" class="d-none">Group Key</th> 
                    <th data-data="FieldKey" data-visible="false" class="d-none">Field Key</th> 
                    <th data-data="Language">Language</th> 
                    <th data-data="Text" >Text</th> 
                    <th data-data="AuditChangeType" data-visible="false" class="d-none">Audit Change Type</th> 
                    <th data-data="AuditChangeBy" data-visible="false" class="d-none">Audit Change By</th> 
                    <th data-data="AuditChangeDate" data-visible="false" class="d-none">Audit Change Date</th> 
                    <th data-sortable="false" width="100">&nbsp;</th>
                </tr> 
                </thead> 
                <tbody></tbody> 
            </table> 
        </div> 
    </div>
</div>

Jlw.ModularContent.Rcl/Areas/ModularContentWizardAdmin/Views/WizardAdmin/_DataTableLanguageListScript.cshtml
@using Newtonsoft.Json
@model Jlw.ModularContent.ModularWizardAdminSettings
<script>
    if (!window.jlwLibLocalizedContentText) {
        window.jlwLibLocalizedContentText = function($target, urlRoot, elemData, $) {
            if (!$) $ = window.jQuery;

            if (!elemData)
                elemData = {};

            $.fn.dataTable.ext.errMode = 'none';
            var t = new libJlwAppBuilder(urlRoot, $target);

            @if (Model?.CanEditLabelText ?? false)
            {
	            @:t.frmEdit = $('#jlwEditFormLocalizedContentText').html();
            }

            @if (Model?.CanInsertLabelText ?? false)
            {
                <text>
                    function fnOnAddRecord(fnOnShow) {
                        function fnShow(o, data) {
                            var oFrm = $(o);
                            $('input[name=GroupKey]', oFrm).val(elemData['GroupKey']);
                            $('input[name=FieldKey]', oFrm).val(elemData['FieldKey']);
                            $('select[name=Language]', oFrm).val('EN');
                            $('input[name=ParentKey]', oFrm).val(elemData['ParentKey']);
                            $('select[name=Language]', oFrm).parent().removeClass('d-none');

                            if (typeof fnOnShow == 'function')
                                fnOnShow(o, data);
                        }
                        return t.onAddRecord(fnShow);
                    }
                </text>
            }

            @if (Model?.CanEditLabelText ?? false)
            {
                <text>
                    function fnOnEditRecord(oBtn, fnOnShow) {
                        function fnShow(o, data) {
                            var oFrm = $(o);
                            $('input[name=GroupKey]', oFrm).val(elemData['GroupKey']);
                            $('input[name=FieldKey]', oFrm).val(elemData['FieldKey']);
                            $('input[name=ParentKey]', oFrm).val(elemData['ParentKey']);
                            $('select[name=Language]', oFrm).parent().addClass('d-none');
                            if (typeof fnOnShow == 'function')
                                fnOnShow(o, data);
                        }
                        return t.onEditRecord(oBtn, fnShow);
                    }

                    t.addDtRowButton('', 'btn-edit', 'fas fa-pencil-alt text-warning', 'btn-outline-secondary', fnOnEditRecord);
                </text>
            }

            @if (Model?.CanDeleteLabelText ?? false)
            {
                @:t.addDtRowButton('', 'btn-delete', 'fas fa-trash-alt text-danger', 'btn-outline-secondary', t.onDeleteRecord);
            }

            @if ((Model?.CanInsertLabelText ?? false) || (Model?.CanEditLabelText ?? false))
            {
                <text>
                    t.optionsWysiwyg = @Html.Raw(JsonConvert.SerializeObject(Model?.TinyMceSettings ?? new object()));

		            // Prevent Bootstrap dialog from blocking focusin
		            document.addEventListener('focusin', (e) => {
			            if (e.target.closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root") !== null) {
				            e.stopImmediatePropagation();
                        }
		            });
                </text>
            }

            t.fnPostDtAjaxData = function(d) {
                d.GroupKey = elemData["GroupKey"];
                d.FieldKey = elemData["FieldKey"];
                d.ParentKey = elemData["ParentKey"];
                d.Language = 'EN';
            }
            t.addDtRenderer(t.dtRenderButtons, [7]);
            var dt = t.initializeDataTable(t.sDtSelector);

            dt.on('error.dt',
                    function(e, settings, techNote, message) {
                        if (console)
                            console.log('An error has been reported by DataTables: ', message);
                    })
                .on('xhr.dt', function ( e, settings, json, xhr ) {
                    var data = xhr["responseJSON"];
                    t.checkAjaxMessage(data);
                } );



            @if (Model?.CanInsertLabelText ?? false)
            {
                @:t.addDtFooterButton(' Add New Record', 'btn-newrecord', 'fa fa-plus', 'btn-primary', fnOnAddRecord);
                @:$('.btn-newrecord').off('click').on('click', fnOnAddRecord);
            }
            t.dtRenderFooterButtons();
            return t;
        }
    }
</script>